const renderCore = require('./render17');

const VERSION = 21;
const POPUP_RE = /(cookie|cookies|consent|gdpr|cookieyes|cky[-_]|cmplz|t-cookie|tildacookie|popup|pop-up|modal|dialog|pum-|popmake|jet-popup|elementor-popup|complianz|onetrust|cookiebot)/i;

function cors(res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  res.setHeader('Access-Control-Max-Age', '86400');
  res.setHeader('Cache-Control', 'no-store');
}

function mockRun(handler, req) {
  return new Promise((resolve, reject) => {
    let statusCode = 200;
    let finished = false;
    const headers = {};
    const done = (kind, body) => {
      if (finished) return;
      finished = true;
      resolve({ statusCode, headers, kind, body });
    };
    const res = {
      setHeader(k, v) { headers[String(k).toLowerCase()] = v; return this; },
      status(code) { statusCode = Number(code) || 200; return this; },
      json(body) { done('json', body); return this; },
      send(body) { done('send', body); return this; },
      end(body) { done('end', body); return this; },
    };
    Promise.resolve(handler(req, res))
      .then(() => { if (!finished) done('end'); })
      .catch(reject);
  });
}

function forward(result, res) {
  for (const [k, v] of Object.entries(result.headers || {})) {
    try { res.setHeader(k, v); } catch {}
  }
  const out = res.status(result.statusCode || 200);
  if (result.kind === 'json') return out.json(result.body);
  if (result.kind === 'send') return out.send(result.body);
  return out.end(result.body);
}

function frameworkOf(snapshot) {
  const layers = Array.isArray(snapshot && snapshot.layers) ? snapshot.layers : [];
  let elementor = 0;
  let tilda = 0;
  for (const layer of layers.slice(0, 1000)) {
    const name = String(layer && layer.name || '').toLowerCase();
    const section = String(layer && layer.sectionId || '').toLowerCase();
    if (/elementor|e-con|e-flex/.test(name + ' ' + section)) elementor++;
    if (/\bt\d{3}\b|t-rec|t396|tn-elem|t-slds|tilda/.test(name + ' ' + section)) tilda++;
  }
  if (elementor >= 2 && elementor > tilda) return 'elementor';
  if (tilda >= 2) return 'tilda';
  return 'generic';
}

function removeKnownPopups(snapshot) {
  if (!snapshot || !Array.isArray(snapshot.layers)) return { snapshot, removed: 0 };

  const blockedContainers = new Set();
  for (const layer of snapshot.layers) {
    if (!layer || layer.kind !== 'container' || !layer.containerKey) continue;
    const probe = `${layer.name || ''} ${layer.text || ''}`;
    if (POPUP_RE.test(probe)) blockedContainers.add(layer.containerKey);
  }

  let changed = true;
  while (changed) {
    changed = false;
    for (const layer of snapshot.layers) {
      if (!layer || layer.kind !== 'container' || !layer.containerKey || !layer.parentContainerKey) continue;
      if (blockedContainers.has(layer.parentContainerKey) && !blockedContainers.has(layer.containerKey)) {
        blockedContainers.add(layer.containerKey);
        changed = true;
      }
    }
  }

  let removed = 0;
  const layers = snapshot.layers.filter(layer => {
    if (!layer) return false;
    const text = String(layer.text || '');
    const name = String(layer.name || '');
    const explicitCookieText = /(?:файл(?:ы|ов)?\s+cookie|используем\s+cookie|настройк[аи]\s+cookie|политик[аи]\s+cookie)/i.test(text);
    const blocked = POPUP_RE.test(name) || explicitCookieText || (layer.parentContainerKey && blockedContainers.has(layer.parentContainerKey));
    if (blocked) removed++;
    return !blocked;
  });

  return { snapshot: { ...snapshot, layers }, removed };
}

module.exports = async function handler(req, res) {
  cors(res);
  if (req.method === 'OPTIONS') return res.status(204).end();
  if (!['GET', 'POST'].includes(req.method)) {
    return res.status(405).json({ ok: false, error: 'Разрешены только GET, POST и OPTIONS' });
  }

  if (req.method === 'GET' && String(req.query && req.query.ping || '') === '1') {
    return res.status(200).json({
      ok: true,
      service: 'browser-renderer',
      version: VERSION,
      architecture: 'unified-v17-core',
      geometryFirst: true,
      popupSuppression: 'conservative-snapshot-filter',
      visualQa: true,
    });
  }

  try {
    const result = await mockRun(renderCore, req);

    // Binary reference screenshots and capture-clips are already generated by the
    // mature Chromium core. Forward them without changing bytes or geometry.
    if (result.kind !== 'json' || !result.body || result.statusCode !== 200 || !result.body.snapshot) {
      return forward(result, res);
    }

    const filtered = removeKnownPopups(result.body.snapshot);
    const snapshot = filtered.snapshot;
    const framework = frameworkOf(snapshot);

    snapshot.rendererVersion = VERSION;
    snapshot.framework = framework;
    snapshot.popupSuppression = true;
    snapshot.geometryPolicy = 'browser-absolute';

    const imageLayers = snapshot.layers.filter(x => x && x.kind === 'image').length;
    return res.status(200).json({
      ...result.body,
      mode: 'browser-snapshot-v21-unified',
      snapshot,
      stats: {
        ...(result.body.stats || {}),
        rendererVersion: VERSION,
        framework,
        layers: snapshot.layers.length,
        sections: Array.isArray(snapshot.sections) ? snapshot.sections.length : 0,
        imageLayers,
        popupLayersRemoved: filtered.removed,
        geometryPolicy: 'browser-absolute',
      },
    });
  } catch (error) {
    return res.status(500).json({ ok: false, error: error && error.message ? error.message : String(error) });
  }
};
